# Generated by Django 5.1.2 on 2024-11-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Taps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='content/')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='taps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taps'),
        ),
    ]
