# Generated by Django 5.1.2 on 2024-11-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='1235gg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='apply/main_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='solutions/main_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Taps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Apply_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='apply/content/')),
                ('type', models.IntegerField(default=1)),
                ('apply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.apply')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='content/')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
            ],
        ),
        migrations.CreateModel(
            name='Sol_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='solutions/content/')),
                ('type', models.IntegerField(default=1)),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solutions')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='taps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taps'),
        ),
    ]
