# Generated by Django 5.1.2 on 2024-11-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sol_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='solutions/')),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solutions')),
            ],
        ),
    ]
