# Generated by Django 5.1.2 on 2025-01-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_history_main_pg_history_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_content',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_content', to='main.history'),
        ),
    ]
