# Generated by Django 5.1.2 on 2024-11-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_solutions_sol_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sol_content',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
