# Generated by Django 5.1.2 on 2025-01-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_history_content_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='solutions/main_img/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_title', to='main.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Solution_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('solution_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_option', to='main.solution_title')),
            ],
        ),
        migrations.CreateModel(
            name='Solution_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('eg_title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('solution_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_details', to='main.solution_title')),
            ],
        ),
    ]
