# Generated by Django 5.1.2 on 2024-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sol_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='content_img',
            field=models.ImageField(default='', upload_to='solutions/main_img/'),
        ),
        migrations.AlterField(
            model_name='sol_content',
            name='content_img',
            field=models.ImageField(upload_to='solutions/content/'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
