# Generated by Django 5.1.2 on 2024-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_solutions_content_img_alter_sol_content_content_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='1235gg', max_length=100)),
            ],
        ),
    ]
