# Generated by Django 5.1.2 on 2024-11-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_ex', models.CharField(default='', max_length=300)),
                ('main_cp', models.TextField(default='')),
                ('main_text', models.TextField(default='')),
                ('content_img', models.ImageField(default='', upload_to='solutions/main_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content_text', models.TextField(default='')),
                ('content_img', models.ImageField(upload_to='solutions/content/')),
                ('type', models.IntegerField(default=1)),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solutions')),
            ],
        ),
    ]
