# Generated by Django 5.1.2 on 2025-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_solution_content_solution_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution_contentop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='solutions/sub_img/')),
            ],
        ),
    ]
