# Generated by Django 5.1.2 on 2024-11-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_apply_apply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='content_img',
            field=models.ImageField(default='', upload_to='apply/main_img/'),
        ),
        migrations.AlterField(
            model_name='apply_content',
            name='content_img',
            field=models.ImageField(upload_to='apply/content/'),
        ),
    ]
