# Generated by Django 5.1.2 on 2025-01-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_solution_contentop'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution_contentop',
            name='solution_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sol_content_op', to='main.solution_content'),
        ),
    ]
