# Generated by Django 5.1.2 on 2025-01-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_solution_contentop_solution_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution_contentop',
            name='solution_content',
        ),
        migrations.AddField(
            model_name='solution_contentop',
            name='Solution_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sol_content_op', to='main.solution_title'),
        ),
    ]
