# Generated by Django 5.1.2 on 2024-11-12 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_apply_content_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_content',
            name='solutions',
        ),
        migrations.AddField(
            model_name='apply_content',
            name='apply',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.apply'),
        ),
    ]
