# Generated by Django 5.1.2 on 2025-01-14 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_solution_contentop_solution_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='solutions/main_img/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_title', to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('project_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_option', to='main.project_title')),
            ],
        ),
        migrations.CreateModel(
            name='Project_contentop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='solutions/sub_img/')),
                ('project_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_content_op', to='main.project_title')),
            ],
        ),
        migrations.CreateModel(
            name='Project_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('eg_title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('project_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proj_details', to='main.project_title')),
            ],
        ),
    ]
