# Generated by Django 5.1.2 on 2024-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_apply_content_solutions_apply_content_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='apply/main_img/'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/main_img/'),
        ),
    ]
