# Generated by Django 5.1.2 on 2025-01-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_title_alter_solution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_pg',
            name='main_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_pg',
            name='sub_script',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
