# Generated by Django 5.1.2 on 2025-01-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_main_pg_main_title_alter_main_pg_sub_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_content',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_contentop',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
