# Generated by Django 5.1.2 on 2025-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_content_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_content',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_option',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project_title',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='project/main_img/'),
        ),
        migrations.AlterField(
            model_name='project_title',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution_title',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
