# Generated by Django 5.1.2 on 2025-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_content',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution_content',
            name='details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution_contentop',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
