# Generated by Django 5.1.2 on 2025-02-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_solution_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_pg',
            name='ceo_name',
            field=models.CharField(blank=True, default='신동연', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_pg',
            name='sub_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
