# Generated by Django 5.1.2 on 2025-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_main_pg_ceo_name_alter_main_pg_sub_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/title_img/'),
        ),
    ]
